import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'
import { Nav } from '~/components/nav'
import { Providers } from '~/components/providers'
import type { Locale } from '~/i18n-config'
import { auth } from '~/server/auth'
import { getTranslations } from '~/lib/get-translations'

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default async function RootLayout({
	children,
	params
}: Readonly<{ children: React.ReactNode; params: Promise<{ lang: Locale }> }>) {
	const session = await auth()
	const { lang } = await params
	const translations = await getTranslations(lang)

	return (
		<html
			suppressHydrationWarning
			lang='en'
			className={`${GeistSans.variable}`}
		>
			<body className='font-roboto flex overflow-y-auto'>
				<Providers translations={translations} session={session}>
					<Nav />
					{children}
				</Providers>
			</body>
		</html>
	)
}
