import '~/globals.css'

import { type Metadata } from 'next'
import { Geist } from 'next/font/google'

import { auth } from '~/server/auth'
import { Providers } from '~/components/providers'
import { Navbar } from '~/components/navbar/navbar'
import { getTranslations } from '~/lib/get-translations'
import type { Locale } from '~/i18n-config'

export const metadata: Metadata = {
  title: 'RecipeChat',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans'
})

export default async function RootLayout({
  children,
  params
}: Readonly<{ children: React.ReactNode; params: Promise<{ lang: Locale }> }>) {
  const session = await auth()
  const { lang } = await params
  const translations = await getTranslations(lang)

  return (
    <html lang={lang} className={`${geist.variable}`}>
      <body className='flex h-svh overflow-hidden'>
        <Providers session={session} translations={translations}>
          <Navbar />

          <div className='flex h-full flex-1 flex-col'>{children}</div>
        </Providers>
      </body>
    </html>
  )
}
