import '~/globals.css'

import { type Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'

import { auth } from '~/server/auth'
import { Providers } from '~/components/providers'
import { Navbar } from '~/app/[lang]/navbar/navbar'
import { getTranslations } from '~/lib/get-translations'
import type { Locale } from '~/i18n-config'
import { ErrorBoundary } from '~/components/error-boundary'
import { AppFooter } from '~/app/[lang]/app-footer'

export const metadata: Metadata = {
  title: 'RecipeChat',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default async function RootLayout({
  children,
  params
}: Readonly<{ children: React.ReactNode; params: Promise<{ lang: Locale }> }>) {
  const session = await auth()
  const { lang } = await params
  const translations = await getTranslations(lang)

  return (
    <html
      suppressHydrationWarning
      lang={lang}
      className={`${GeistSans.variable}`}
    >
      <body className='h-svh overflow-y-auto'>
        <div className='mx-auto flex w-full max-w-2xl flex-col'>
          <Providers session={session} translations={translations}>
            <ErrorBoundary>
              <header className='sticky top-0 z-30'>
                <Navbar />
              </header>
              <main className='flex min-h-0 flex-1 flex-col'>
                {children}
              </main>
              <AppFooter />
            </ErrorBoundary>
          </Providers>
        </div>
      </body>
    </html>
  )
}
