import Head from 'next/head'
import { useRouter } from 'next/router'
import Layout from '../../components/Layout'
import RecipeById from '../../features/recipes/ById'

export default function Recipe() {
  const router = useRouter()
  const { id, name } = router.query

  return (
    <div className=''>
      <Head>
        <title>Listy - {name}</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <RecipeById id={parseInt(id as string)} />
      </Layout>
    </div>
  )
}
