import Head from 'next/head'
import Layout from '../../components/Layout'
import { ListRecent } from '../../features/recipes/ByUserId'

export default function Recipes() {
  return (
    <>
      <Head>
        <title>Listy - Recipes</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ListRecent />
      </Layout>
    </>
  )
}
