import Head from 'next/head'
import Layout from '../components/Layout'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Listy - Dashboard</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <p className=''>Authenticated</p>
      </Layout>
    </>
  )
}
