import Head from 'next/head'
import Layout from './layout'
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import { GetServerSideProps } from 'next'

async function http<T>(request: RequestInfo): Promise<T> {
  const response = await fetch(request)
  return await response.json()
}

type Post = {
  id: string
  userId: number
  title: string
  body: string
}

const request = new Request('http://localhost:3000/api/recipes', {
  method: 'post',
  body: JSON.stringify({
    userId: 1
  }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})

const recipeKeys = {
  all: ['recipes'] as const
}

export async function getServerSideProps() {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(recipeKeys.all, () => http<Post>(request))

  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  }
}

export default function Dashboard() {
  const { data } = useQuery({
    queryKey: ['posts'],
    queryFn: () => http<Post>(request)
  })
  console.log(data)
  const recentRecipes = miniRecipeItem.slice(0, 3).map((item) => (
    <div key={item.id} className=''>
      <h3 className=''>{item.name}</h3>
    </div>
  ))
  return (
    <>
      <Head>
        <title>Listy - Dashboard</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main className='text-white container mx-auto flex flex-col items-center justify-center min-h-screen'>
          <div className=''>
            <h1 className=''>recent lists</h1>
            {recentRecipes}
          </div>
        </main>
      </Layout>
    </>
  )
}

export const miniRecipeItem: MiniItemType[] = [
  {
    id: 'abc',
    name: 'Jalapeño Cilantro Salsa',
    photo: [
      'https://s23209.pcdn.co/wp-content/uploads/2015/07/IMG_2325edit.jpg'
    ]
  },
  {
    id: 'bcd',
    name: 'Easy Homemade Ramen Bowls {Best Ramen Recipe}',
    photo: [
      'https://www.killingthyme.net/wp-content/uploads/2015/10/homemade-ramen-bowl-3.jpg'
    ]
  },
  {
    id: 'cde',
    name: 'Perfect Pumpkin Pie',
    photo: [
      'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.allrecipes.com%2Frecipe%2F23439%2Fperfect-pumpkin-pie%2F&psig=AOvVaw2OWpeEc7HrDY1YKhG45kQn&ust=1664088858803000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPiv7ZzsrPoCFQAAAAAdAAAAABAD'
    ]
  },
  {
    id: 'cde',
    name: 'Pozole Verde',
    photo: [
      'https://www.foodandwine.com/thmb/wjxIwx_fu9oLRLdXQ8ROMoFfT7A=/2250x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mexican-Chicken-Pozole-Verde-FT-RECIPE0822-2000-1453cc93dff84f2e8c4e47a68dfaad48.jpg'
    ]
  }
]

export type MiniItemType = {
  name: string
  id: string
  photo: string[]
}
