import Head from 'next/head'
import Layout from './layout'
import { trpc } from '../utils/trpc'
import { CreateRecipePopover } from '../features/recipes/Create'

export default function Dashboard() {
  const {
    data: recipes,
    isError,
    isSuccess
  } = trpc.recipeList.useQuery({ userId: 1 })

  if (isError) {
    return 'Something went wrong'
  }

  if (isSuccess) {
    const recentRecipes = recipes.map((item) => (
      <div key={item.recipe.id} className=''>
        <h3 className=''>{item.recipe.name}</h3>
      </div>
    ))

    return (
      <>
        <Head>
          <title>Listy - Dashboard</title>
          <meta name='description' content='Generated by create-t3-app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Layout>
          <main className='container mx-auto flex flex-col items-center justify-center min-h-screen'>
            <div className=''>
              <h1 className=''>recent lists</h1>
              <CreateRecipePopover />

              {recentRecipes}
            </div>
          </main>
        </Layout>
      </>
    )
  }

  return <p>is loading...</p>
}
