import Head from 'next/head'
import React from 'react'
import Layout from '../components/Layout'
import { ListByUserId } from '../features/list/ByUserId'

export default function ListRoute() {
  return (
    <>
      <Head>
        <title>Listy - List</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ListByUserId />
      </Layout>
    </>
  )
}
