import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Layout from './layout'

function Lists() {
  return (
    <>
      <Head>
        <title>Listy - Dashboard</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main className='text-white mx-auto grid grid-cols-2 min-h-screen gap-5 py-4 px-5'>
          {lists.map((list) => (
            <div className='card ' key={list.id}>
              {list.photos.length && list.photos[0] && (
                <Image
                  alt={list.name}
                  src={list.photos[0]}
                  className='object-cover rounded-lg'
                  width={200}
                  height={160}
                />
              )}
              <h3 className=''>{list.name}</h3>
            </div>
          ))}
        </main>
      </Layout>
    </>
  )
}

export default Lists

export type ListType = {
  id: string
  name: string
  tags: string[]
  lastViewed: string
  photos: string[]
  isFavorite: boolean
}

const lists: ListType[] = [
  {
    id: 'abc',
    isFavorite: true,
    lastViewed: 'asdfasdf',
    name: 'dinner, lunch and breakie for a week',
    tags: ['lunch', 'dinner', 'breakfast'],
    photos: [
      'https://s23209.pcdn.co/wp-content/uploads/2015/07/IMG_2325edit.jpg',
      'https://www.killingthyme.net/wp-content/uploads/2015/10/homemade-ramen-bowl-3.jpg',
      'https://www.foodandwine.com/thmb/wjxIwx_fu9oLRLdXQ8ROMoFfT7A=/2250x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mexican-Chicken-Pozole-Verde-FT-RECIPE0822-2000-1453cc93dff84f2e8c4e47a68dfaad48.jpg'
    ]
  },
  {
    id: 'bcd',
    isFavorite: false,
    lastViewed: 'asdfasdf',
    name: 'dinner, lunch and breakie for a week and has a longer name',
    tags: [],
    photos: [
      'https://s23209.pcdn.co/wp-content/uploads/2015/07/IMG_2325edit.jpg',
      'https://www.killingthyme.net/wp-content/uploads/2015/10/homemade-ramen-bowl-3.jpg',
      'https://www.foodandwine.com/thmb/wjxIwx_fu9oLRLdXQ8ROMoFfT7A=/2250x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mexican-Chicken-Pozole-Verde-FT-RECIPE0822-2000-1453cc93dff84f2e8c4e47a68dfaad48.jpg'
    ]
  },
  {
    id: 'd',
    isFavorite: false,
    lastViewed: 'asdfasdf',
    name: 'dinner, lunch and breakie for a week',
    tags: ['lunch'],
    photos: [
      'https://s23209.pcdn.co/wp-content/uploads/2015/07/IMG_2325edit.jpg',
      'https://www.killingthyme.net/wp-content/uploads/2015/10/homemade-ramen-bowl-3.jpg',
      'https://www.foodandwine.com/thmb/wjxIwx_fu9oLRLdXQ8ROMoFfT7A=/2250x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mexican-Chicken-Pozole-Verde-FT-RECIPE0822-2000-1453cc93dff84f2e8c4e47a68dfaad48.jpg'
    ]
  },
  {
    id: 'a',
    isFavorite: true,
    lastViewed: 'asdfasdf',
    name: 'dinner, lunch and breakie for a week',
    tags: ['dinner', 'breakfast'],
    photos: [
      'https://s23209.pcdn.co/wp-content/uploads/2015/07/IMG_2325edit.jpg',
      'https://www.killingthyme.net/wp-content/uploads/2015/10/homemade-ramen-bowl-3.jpg',
      'https://www.foodandwine.com/thmb/wjxIwx_fu9oLRLdXQ8ROMoFfT7A=/2250x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mexican-Chicken-Pozole-Verde-FT-RECIPE0822-2000-1453cc93dff84f2e8c4e47a68dfaad48.jpg'
    ]
  }
]
