import '~/globals.css'

import { type Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { cookies } from 'next/headers'

import { auth } from '~/server/auth'
import { Providers } from '~/components/providers'
import { Navbar } from '~/app/navbar/navbar'
import { getTranslations } from '~/lib/get-translations'
import { ErrorBoundary } from '~/components/error-boundary'
import { AppFooter } from '~/app/app-footer'
import { LOCALE_COOKIE_NAME, getLocaleFromCookie } from '~/lib/locale'

export const metadata: Metadata = {
  title: 'RecipeChat',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default async function RootLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth()
  const cookieStore = await cookies()
  const locale = getLocaleFromCookie(cookieStore.get(LOCALE_COOKIE_NAME)?.value)
  const translations = await getTranslations(locale)

  return (
    <html
      suppressHydrationWarning
      lang={locale}
      className={`${GeistSans.variable}`}
    >
      <body className='h-svh overflow-hidden'>
        <div className='mx-auto flex h-full w-full max-w-2xl flex-col'>
          <Providers session={session} translations={translations} locale={locale}>
            <ErrorBoundary>
              <header className='sticky top-0 z-30'>
                <Navbar />
              </header>
              <main className='flex min-h-0 flex-1 flex-col overflow-y-auto'>
                {children}
              </main>
              <AppFooter />
            </ErrorBoundary>
          </Providers>
        </div>
      </body>
    </html>
  )
}
