import Head from 'next/head'
import { useTheme } from './theme-toggle'

export const MyHead = ({ title }: { title: string }) => {
  const { theme } = useTheme()

  let icon = '/light-mode-favicon.png'
  if (theme === 'night') {
    icon = '/dark-mode-favicon.png'
  }

  return (
    <Head>
      <title>{title}</title>
      <meta name='description' content='Generated by create-t3-app' />
      <meta name='viewport' content='width=device-width, initial-scale=1.0' />

      <link type='image/png' rel='icon' href={icon} />
    </Head>
  )
}
