import Head from 'next/head'

function getBrowser() {
  let tem
  const ua = navigator.userAgent
  let M =
    ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i) ||
    []
  if (/trident/i.test(M[1])) {
    tem = /\brv[ :]+(\d+)/g.exec(ua) || []
    return { name: 'IE', version: tem[1] || '' }
  }
  if (M[1] === 'Chrome') {
    tem = ua.match(/\b(OPR|Edge)\/(\d+)/)
    if (tem != null)
      return { name: tem[1].replace('OPR', 'Opera'), version: tem[2] }
  }
  M = M[2] ? [M[1], M[2]] : [navigator.appName, navigator.appVersion, '-?']
  if ((tem = ua.match(/version\/(\d+)/i)) != null) M.splice(1, 1, tem[1])
  return { name: M[0], version: M[1] }
}

export const MyHead = ({ title }: { title: string }) => {
  let iosMetaTag = null
  if (typeof window === 'object' && getBrowser().name === 'Safari') {
    iosMetaTag = <meta name='viewport' content='viewport-fit=cover'></meta>
  }

  return (
    <Head>
      <title>{title}</title>
      <meta name='description' content='Generated by create-t3-app' />
      {/* {iosMetaTag} */}
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}
