import Head from 'next/head'

export const MyHead = ({ title }: { title: string }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name='description' content='Generated by create-t3-app' />
      {/* {iosMetaTag} */}
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}
