import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { type Metadata } from 'next'
import { PublicNavbar } from '~/components/nav'
import { Providers } from '~/components/providers'
import type { Locale } from '~/i18n-config'
import { auth } from '~/server/auth'
import { getTranslations } from '~/utils/get-translations'

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default async function RootLayout({
	children,
	params
}: Readonly<{ children: React.ReactNode; params: Promise<{ lang: Locale }> }>) {
	const session = await auth()
	const { lang } = await params
	const translations = await getTranslations(lang)

	return (
		<html lang='en' className={`${GeistSans.variable}`}>
			<body className='font-roboto flex overflow-y-auto'>
				<Providers translations={translations} session={session}>
					<div className='relative max-w-full flex-1'>
						<div className='fixed top-0 z-10 flex w-full justify-center border-b border-b-base-300 bg-gradient-to-b from-base-100 to-base-100/70 text-base-content bg-blend-saturation backdrop-blur transition-all duration-300'>
							<PublicNavbar />
						</div>
						<main className='transition-width relative flex h-[100svh] w-full flex-1 flex-col items-stretch'>
							{children}
						</main>
					</div>
				</Providers>
			</body>
		</html>
	)
}
